---
# easy Ubuntu nginx playbook as an example.
# this is a test for ec2 user-data  
# local.yml is used for pull-based Ansible setup.

- hosts: localhost 
  sudo: True

  tasks:

     - name: just check if local is updated.
       shell: echo "Hello Ansible."
       register: output
     - debug: msg= "{{ output }}"
     - name: commiting changes
       shell: echo "Hello Ansible"


